// <auto-generated />
namespace freccamp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_amountpaid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_amountpaid));
        
        string IMigrationMetadata.Id
        {
            get { return "201606031238034_add_amountpaid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
