// <auto-generated />
namespace freccamp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_registration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_registration));
        
        string IMigrationMetadata.Id
        {
            get { return "201605230106422_add_registration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
